postgres:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: fabo
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
postgres_logs:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: test
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
postgres_notifier:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: test
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
postgres_crm:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: test
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
postgres_affiliate:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: etop_dev
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
redis:
  host: redis
  port: "6379"
  username: ""
  password: ""
http:
  host: ""
  port: 8080
kafka:
  enabled: true
  brokers: ["kafka:9092"]
  topic_prefix: d
upload:
  dir_import_shop_order: /tmp
  dir_import_shop_product: /tmp
export:
  url_prefix: http://localhost:8080
  dir_export: /tmp
telegram_bot:
  token: ""
  chats: {}
smtp:
  host: ""
  port: 0
  username: ""
  password: ""
  encrypt: ""
  from_address: ""
email:
  enabled: false
  reset_password_url: https://etop.d.etop.vn/reset-password
  email_verification_url: https://etop.d.etop.vn/verify-email
sms:
  enabled: true
  mock: true
  vietguys:
    brand_name: ""
    username: ""
    api_key: ""
captcha:
  secret: 6LcVOnkUAAAAALKlDJY_IYfQUmBfD_36azKtCv9P
  local_passcode: recaptcha_token
ghn:
  env: test
  account_default:
    token: 5b20c7c194c06b03b2010913
    account_id: 503809
  account_ext:
    token: ""
    account_id: 0
ghn_webhook:
  host: ""
  port: 9022
  endpoint: http://callback-url
ghtk:
  env: test
  account_default:
    account_id: S1858017
    token: 877F63B8596d32e1B0b2B0FcB0cF8E2980B28777
  account_same_price:
    account_id: S1858017
    token: 877F63B8596d32e1B0b2B0FcB0cF8E2980B28777
  account_same_price_2:
    account_id: S1858017
    token: 877F63B8596d32e1B0b2B0FcB0cF8E2980B28777
ghtk_webhook:
  host: ""
  port: 9032
vtpost:
  env: test
  account_default:
    username: tuan@eye-solution.vn
    password: 1234@5678
vtpost_webhook:
  host: ""
  port: 9042
ahamove:
  env: test
  name: ahamove_test
  api_key: 860160f707a7a8afc7bffa3e54630f40
ahamove_webhook:
  host: ""
  port: 9052
ecom:
  http:
    host: ""
    port: 8100
  main_site: http://localhost:8100
haravan:
  api_key: 808d1d36611d40888b715bd21ef2fe5d
  secret: a467cac64daee1dc4edcce170d06e78b
vtpay:
  env: test
  access_code: d41d8cd98f00b204e9800998ecf8427eb36ee15cfa9bbaf984868d25cc21215a
  secret_key: d41d8cd98f00b204e9800998ecf8427e1c371a7425bf2b1a5fdf5a83c5371a40
  merchant_code: ETOP
sadmin_token: PZJvDAY2.sadmin.HXnnEkdV
serve_doc: true
env: dev
url:
  auth: http://localhost:8080
  main_site: http://localhost:8080
third_party_host: https://etop.d.etop.vn
secret: secret
vtiger:
  service_url: http://vtiger/webservice.php
  username: admin
  api_key: ""
  mapping_file: /home/ngoc/work/src/etop.vn/backend/cmd/etop-server/config/field_mapping_example.json
vht:
  username: ""
  password: ""
invitation:
  secret: IBVEhECSHtJiBoxQKOVafHW58zt9qRK7
white_label:
  imgroup:
    sms:
      api_key: ""
flag_enable_permission: all

