version: "3.5"
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    shm_size: 4GB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - $PROJECT_DIR/backend/db:/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - POSTGRES_DATA=/var/lib/postgresql/data/pgdata

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  redis_data:
    external: false
  postgres_data:
    external: false